#!/bin/sh

# Copies PO files from a PgFoundry repository structure to a PostgreSQL
# source tree.
#
# Usage: cp-po [-n] SOURCEDIR DESTDIR
#
# Written by Peter Eisentraut
# Public domain

set -e

me=$(basename $0)

run=true

TEMP=$(getopt n "$@")
eval set -- "$TEMP"

while true; do
	case $1 in
		-n)	run=false; shift;;
		--)	shift; break;;
	esac
done

srcdir=$1
if [ -z "$srcdir" ]; then
	echo "$me: no source directory specified" 1>&2
	exit 1
fi

destdir=$2
if [ -z "$destdir" ]; then
	echo "$me: no destination directory specified" 1>&2
	exit 1
fi

nls_mks=$(find "$destdir" -name nls.mk)

for srcfile in $(find "$srcdir" -name '*.po'); do
	base=$(echo X"$srcfile" | sed "s,^X$srcdir/*,,")
	lang=$(expr $base : '\([a-z][a-zA-Z_]*\)')
	srccat=$(expr $base : '.*/\([^/]*\)\.po$')

	if ! msgfmt -o /dev/null -c -v $srcfile 2>/dev/null; then
		echo "$me: $srcfile has errors" 1>&2
		msgfmt -o /dev/null -c -v $srcfile
		exit 1
	fi

	for y in $nls_mks; do
		destcat=$(cat $y | sed -n 's/CATALOG_NAME.*:*= *\([^ ]*\)$/\1/p')
		if [ -z "$destcat" ]; then
			echo "$me: could not determine catalog name from $y; skipped" 1>&2
			continue
		fi
		if [ "$srccat" = "$destcat" ]; then
			targetdir=$(echo $y | sed 's,nls\.mk$,po,')
			targetfile=$targetdir/$lang.po
			if [ ! -e $targetfile ]; then
				echo "NEW: $targetfile --- file will be copied, but do \"cvs add\" and fix $y by hand" 1>&2
			fi
			if [ ! -e $targetfile ] || ! diff -I '\$\(Header\|Id\|PostgreSQL\):.*\$' $srcfile $targetfile >/dev/null; then
				echo " $srcfile --> $targetfile"
				$run && { cat $srcfile | sed 's/^\(# *\)$Id/\1pgtranslation Id/' >$targetfile; chmod 644 $targetfile; }
			fi
		fi
	done
done
