#!/usr/bin/perl

use strict;
use warnings;

my $dir = $ARGV[0] || '.';

print <<_EOF_;
<?xml version='1.0'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style type="text/css">
h1 { color: #EC5800; }
h2 { border-bottom: solid 10px #0092C3; }
a { color: #0092C3; }
.newpo { color: #666; visibility: visible; }
.qualifiedpo { background-color: #FFFF00; }
.fullpo { background-color: #00FF00; }
.errorpo { background-color: #FF0000; }
</style>
<script type="text/javascript">
function getStyleClass (className) {
	for (var s = 0; document.styleSheets.length > s; s++)
	{
		if(document.styleSheets[s].rules)
		{
			for (var r = 0; document.styleSheets[s].rules.length > r; r++)
			{
				if (document.styleSheets[s].rules[r].selectorText == '.' + className)
				{
					return document.styleSheets[s].rules[r];
				}
			}
		}
		else if(document.styleSheets[s].cssRules)
		{
			for (var r = 0; document.styleSheets[s].cssRules.length > r; r++)
			{
				if (document.styleSheets[s].cssRules[r].selectorText == '.' + className)
					return document.styleSheets[s].cssRules[r];
			}
		}
	}
	
	return null;
}

</script>
<title>NLS Status Tables</title>
</head>

<body>
<h1>NLS Status Tables</h1>

<p>The tables below shows which areas of the PostgreSQL source are prepared 
for translation, and the progress of those translations. The numbers are 
percents of translated messages. By following the links, you can download 
freshly baked PO files that are merged up against the latest program sources. 
No PostgreSQL source tree is needed for translation work.</p>

<p>The <span class='qualifiedpo'>highlighted</span> boxes are the files that 
have a sufficient fraction of strings translated to be considered for release. 
Files that are <span class='fullpo'>100%</span> translated are specially 
highlighted. All other files will not be part of the PostgreSQL release.</p>

<p>The grey numbers are translations that do not exist yet, but where this
web site has initialized the translations files for you with data from the
existing translations for the same language.</p>

<p>You can work in several branches. Please see the status information below 
and follow the announcements on the <a 
href="http://lists.pgfoundry.org/pipermail/pgtranslation-translators/">mailing 
list</a> about when a branch is about to be released.</p>

<ul>
_EOF_

my %branch_status = (
    '8.3-branch' => 'maintenance',
    '8.4-branch' => 'maintenance',
    '9.0-branch' => 'maintenance',
    '9.1-branch' => 'maintenance',
    '9.2-branch' => 'translate this now',
);

my @branches = map { m!table-([^/]+).html$! && $1 } reverse sort glob("$dir/table-*.html");

my ($b, $title);

foreach $b (@branches) {
    ($title = $b) =~ tr/-/ /;
    print "<li><a href='#t${b}-branch'>$title</a> &mdash; $branch_status{$b}</li>\n";
}

print <<_EOF_;
</ul>

<p>Other information:
<a href="http://wiki.postgresql.org/wiki/NLS">contributor/translator information (wiki)</a> |
<a href="http://www.pgfoundry.org/projects/pgtranslation/">PgFoundry project</a>
</p>

<!-- FIXME:
<p>Display options:
<a href='' onclick="javascript:getStyleClass('newpo').style.visibility = 'visible';">show new</a> |
<a href='' onclick="javascript:getStyleClass('newpo').style.visibility = 'hidden';">hide new</a>
</p>
-->
_EOF_

foreach $b (@branches) {
    ($title = $b) =~ tr/-/ /;
    print "<h2><a name='t${b}-branch'></a>", ucfirst($title), "</h2>\n";

    open F, "$dir/table-${b}.html" or die $!;
    print foreach <F>;
    close F;

    print "<p><a href='qualified-list-$b.txt'>qualified list</a></p>\n" if -e "$dir/qualified-list-$b.txt";
}

print <<_EOF_;
</body>
<script type="text/javascript">
var elements = document.getElementsByClassName('timestamp');
var i;
for (i = 0; i < elements.length; i++) {
    var s = elements[i].textContent;
    var d = new Date(Date.parse(s));
    elements[i].textContent = d.toString();
    elements[i].setAttribute('title', d.toUTCString());
}
</script>
</html>
_EOF_
