#! /usr/bin/env bash
shopt -s nullglob

echo "================="
echo "NLS update starts"
echo "================="
date -u +%FT%T

me=$(basename $0)

set -ex

MYDIR=$(cd $(dirname $0) && pwd)
WEBDIR=$MYDIR/../../htwork
CVSDIR=$(cd $MYDIR/../../cvs && pwd)

GMAKE=make
which gmake >/dev/null && GMAKE=gmake
export GMAKE

active_branches="current 8.4-branch 8.3-branch 8.2-branch 8.1-branch 8.0-branch 7.4-branch"

if [ -n "$1" ]; then
	active_branches=$1
	force=true
fi

lock="$PWD/lock"
test -e "$lock" && exit 77
trap 'rm -f $tmp $lock' EXIT ERR SIGHUP SIGINT SIGPIPE SIGTERM
touch "$lock"

for branch in $active_branches; do
	tmp=`mktemp /tmp/$me.XXXXXX`

	PGSRC=$CVSDIR/postgresql-$branch

	pushd $PGSRC
	cvs -q update | tee "$tmp"
	if egrep -q '^C ' "$tmp"; then
		rm $(sed -n 's/^C //p' "$tmp")
		cvs -q update | tee "$tmp"
	fi
	popd

	rm -rf $PGSRC.work
	cp -R $PGSRC $PGSRC.work

	if [ -d "$CVSDIR/messages-$branch" ]; then
		(cd $CVSDIR/messages-$branch; cvs -q update) | tee -a "$tmp"
		$MYDIR/../cp-po -f -k $CVSDIR/messages-$branch $PGSRC.work
	fi

	if [ "$force" != true ] && ! egrep -q '^(U|P) ' "$tmp"; then
		continue
	fi

	rm -f "$tmp"

	pushd $PGSRC.work
	./configure --prefix=$MYDIR/pg-install --cache=/dev/null --enable-nls --with-includes=/usr/local/include --with-libraries=/usr/local/lib \
		--with-perl --with-tcl
	popd

	# remove old data in case it contained garbage
	rm -rf $WEBDIR/po-$branch $WEBDIR/table-$branch.html

	mkdir -p $WEBDIR/po-$branch
	files=`find $PGSRC.work -name nls.mk`
	$MYDIR/pg-make-po -o $WEBDIR/po-$branch -v $branch $files

	(cd $WEBDIR/po-$branch && $MYDIR/nls-status-table -U po-$branch *.pot *.po >$WEBDIR/table-$branch.html)

#	$MYDIR/pg-make-conflicts $branch $MYDIR $WEBDIR

	$MYDIR/nls-status-page $WEBDIR > $WEBDIR/index.html
	rsync -l -r --delete --delete-excluded --exclude='table-*.html' $WEBDIR/ ~/htdocs/
done

date -u +%FT%T
